### ISSUE TITLE
Is there real support for Python 3?

### ISSUE THREAD

**Issue by vlcinsky** [PitchBook/pylambda#1]
`README.rst` declares in requirements `Python 2.7.x OR Python 3.x`

As far as I am aware of, AWS Lambda does support only Python 2.7.x.

For that reason the information from `README.rst` confuses me and brings questions:

- is AWS Lambda supporting Python 3?
- do you expect to test some code locally using Python 3 and consider it tested for running on AWS Lambda as tested?

**Comment by pb-nickames** [comment]
Sorry about the confusion.

AWS currently only supports Python 2.7

Pylambda does work locally with Python 3.

I'll update the readme to better clarify this.

**Comment by pb-nickames** [comment]
Updated README to better reflect Python 2.7 as the environment to work with.

9737bd3d61527a4abfdcf5d7875acc034ef64c16
